language:
  - python
  - node_js

python:
  - "3.7"
  - "3.8"

node_js:
  - 12

services:
  - redis-server

install:
  - nvm use 12
  - node --version
  - npm --version
  - npm install
  - npm run build
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements-pip3.txt

script:
  - pytest -v test/

after_success:
  - codecov