language: python

python:
  - "3.7"
  - "3.8"

services:
  - redis-server

install:
  - nvm install 12
  - nvm use 12
  - npm install
  - npm run build
  - pip install codecov
  - pip install pytest-cov
  - pip install -r requirements-pip3.txt

script:
  - pytest -v test/

after_success:
  - codecov